### ISSUE TITLE
slugify

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/generator-plugin#7]
Does this actually work? https://github.com/assemble/generator-plugin/blob/master/app/index.js#L50

I don't see anywhere that `slugify` is being mixed into lodash. This is an [underscore.string ](https://github.com/epeli/underscore.string) method. sorry if I'm missing something...

**Comment by jonschlinkert** [comment]
or is this a `slugify` method being passed in from yeoman? which I would think would have to be on the `this._` object..?

**Comment by doowb** [comment]
`slugify` must be coming from yeoman. It works when I test it by naming my plugin something like `sweet plugin` and it gives the name as `assemble-plugin-sweet-plugin`.

**Comment by jonschlinkert** [comment]
that's interesting that the naked `_.` works in templates. I need to look at how it's mixed in. thx
